# Generated by Django 5.1.1 on 2024-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, default='', max_length=100)),
                ('is_fetched', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['recipient', 'id'],
            },
        ),
    ]
