//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessagesBulkDeleteFormattedCreateParamsFormat.
const (
	MessagesBulkDeleteFormattedCreateParamsFormatDotJson MessagesBulkDeleteFormattedCreateParamsFormat = ".json"
)

// Defines values for MessagesFetchNewFormattedCreateParamsFormat.
const (
	MessagesFetchNewFormattedCreateParamsFormatDotJson MessagesFetchNewFormattedCreateParamsFormat = ".json"
)

// Defines values for MessagesFormattedListParamsFormat.
const (
	MessagesFormattedListParamsFormatDotJson MessagesFormattedListParamsFormat = ".json"
)

// Defines values for MessagesFormattedCreateParamsFormat.
const (
	MessagesFormattedCreateParamsFormatDotJson MessagesFormattedCreateParamsFormat = ".json"
)

// Defines values for MessagesFormattedDestroyParamsFormat.
const (
	MessagesFormattedDestroyParamsFormatDotJson MessagesFormattedDestroyParamsFormat = ".json"
)

// Defines values for MessagesFormattedRetrieveParamsFormat.
const (
	MessagesFormattedRetrieveParamsFormatDotJson MessagesFormattedRetrieveParamsFormat = ".json"
)

// Defines values for MessagesFormattedPartialUpdateParamsFormat.
const (
	MessagesFormattedPartialUpdateParamsFormatDotJson MessagesFormattedPartialUpdateParamsFormat = ".json"
)

// Defines values for MessagesFormattedUpdateParamsFormat.
const (
	MessagesFormattedUpdateParamsFormatDotJson MessagesFormattedUpdateParamsFormat = ".json"
)

// Defines values for RootFormattedRetrieveParamsFormat.
const (
	DotJson RootFormattedRetrieveParamsFormat = ".json"
)

// Message defines model for Message.
type Message struct {
	CreateTime  *time.Time `json:"create_time,omitempty"`
	Id          *int       `json:"id,omitempty"`
	IsFetched   *bool      `json:"is_fetched,omitempty"`
	MessageBody *string    `json:"message_body,omitempty"`
	Recipient   string     `json:"recipient"`
	Url         *string    `json:"url,omitempty"`
}

// PaginatedMessageList defines model for PaginatedMessageList.
type PaginatedMessageList struct {
	Count    int       `json:"count"`
	Next     *string   `json:"next"`
	Previous *string   `json:"previous"`
	Results  []Message `json:"results"`
}

// PatchedMessage defines model for PatchedMessage.
type PatchedMessage struct {
	CreateTime  *time.Time `json:"create_time,omitempty"`
	Id          *int       `json:"id,omitempty"`
	IsFetched   *bool      `json:"is_fetched,omitempty"`
	MessageBody *string    `json:"message_body,omitempty"`
	Recipient   *string    `json:"recipient,omitempty"`
	Url         *string    `json:"url,omitempty"`
}

// MessagesListParams defines parameters for MessagesList.
type MessagesListParams struct {
	// Page A page number within the paginated result set.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// IsFetched True returns the messages that has been fetched and False the messages that has not. Used to filter the returned messages.
	IsFetched *bool `form:"is_fetched,omitempty" json:"is_fetched,omitempty"`

	// Recipient The recipient of the message. Used to filter the returned messages.
	Recipient *string `form:"recipient,omitempty" json:"recipient,omitempty"`

	// FromId The lowest id value to be returned. Used to filter the returned messages.
	FromId *int `form:"from_id,omitempty" json:"from_id,omitempty"`

	// ToId The highest id value to be returned. Used to filter the returned messages.
	ToId *int `form:"to_id,omitempty" json:"to_id,omitempty"`
}

// MessagesBulkDeleteCreateJSONBody defines parameters for MessagesBulkDeleteCreate.
type MessagesBulkDeleteCreateJSONBody = []int

// MessagesBulkDeleteFormattedCreateJSONBody defines parameters for MessagesBulkDeleteFormattedCreate.
type MessagesBulkDeleteFormattedCreateJSONBody = []int

// MessagesBulkDeleteFormattedCreateParamsFormat defines parameters for MessagesBulkDeleteFormattedCreate.
type MessagesBulkDeleteFormattedCreateParamsFormat string

// MessagesFetchNewFormattedCreateParamsFormat defines parameters for MessagesFetchNewFormattedCreate.
type MessagesFetchNewFormattedCreateParamsFormat string

// MessagesFormattedListParams defines parameters for MessagesFormattedList.
type MessagesFormattedListParams struct {
	// Page A page number within the paginated result set.
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// IsFetched True returns the messages that has been fetched and False the messages that has not. Used to filter the returned messages.
	IsFetched *bool `form:"is_fetched,omitempty" json:"is_fetched,omitempty"`

	// Recipient The recipient of the message. Used to filter the returned messages.
	Recipient *string `form:"recipient,omitempty" json:"recipient,omitempty"`

	// FromId The lowest id value to be returned. Used to filter the returned messages.
	FromId *int `form:"from_id,omitempty" json:"from_id,omitempty"`

	// ToId The highest id value to be returned. Used to filter the returned messages.
	ToId *int `form:"to_id,omitempty" json:"to_id,omitempty"`
}

// MessagesFormattedListParamsFormat defines parameters for MessagesFormattedList.
type MessagesFormattedListParamsFormat string

// MessagesFormattedCreateParamsFormat defines parameters for MessagesFormattedCreate.
type MessagesFormattedCreateParamsFormat string

// MessagesFormattedDestroyParamsFormat defines parameters for MessagesFormattedDestroy.
type MessagesFormattedDestroyParamsFormat string

// MessagesFormattedRetrieveParamsFormat defines parameters for MessagesFormattedRetrieve.
type MessagesFormattedRetrieveParamsFormat string

// MessagesFormattedPartialUpdateParamsFormat defines parameters for MessagesFormattedPartialUpdate.
type MessagesFormattedPartialUpdateParamsFormat string

// MessagesFormattedUpdateParamsFormat defines parameters for MessagesFormattedUpdate.
type MessagesFormattedUpdateParamsFormat string

// RootFormattedRetrieveParamsFormat defines parameters for RootFormattedRetrieve.
type RootFormattedRetrieveParamsFormat string

// MessagesCreateJSONRequestBody defines body for MessagesCreate for application/json ContentType.
type MessagesCreateJSONRequestBody = Message

// MessagesCreateFormdataRequestBody defines body for MessagesCreate for application/x-www-form-urlencoded ContentType.
type MessagesCreateFormdataRequestBody = Message

// MessagesCreateMultipartRequestBody defines body for MessagesCreate for multipart/form-data ContentType.
type MessagesCreateMultipartRequestBody = Message

// MessagesBulkDeleteCreateJSONRequestBody defines body for MessagesBulkDeleteCreate for application/json ContentType.
type MessagesBulkDeleteCreateJSONRequestBody = MessagesBulkDeleteCreateJSONBody

// MessagesBulkDeleteFormattedCreateJSONRequestBody defines body for MessagesBulkDeleteFormattedCreate for application/json ContentType.
type MessagesBulkDeleteFormattedCreateJSONRequestBody = MessagesBulkDeleteFormattedCreateJSONBody

// MessagesFormattedCreateJSONRequestBody defines body for MessagesFormattedCreate for application/json ContentType.
type MessagesFormattedCreateJSONRequestBody = Message

// MessagesFormattedCreateFormdataRequestBody defines body for MessagesFormattedCreate for application/x-www-form-urlencoded ContentType.
type MessagesFormattedCreateFormdataRequestBody = Message

// MessagesFormattedCreateMultipartRequestBody defines body for MessagesFormattedCreate for multipart/form-data ContentType.
type MessagesFormattedCreateMultipartRequestBody = Message

// MessagesPartialUpdateJSONRequestBody defines body for MessagesPartialUpdate for application/json ContentType.
type MessagesPartialUpdateJSONRequestBody = PatchedMessage

// MessagesPartialUpdateFormdataRequestBody defines body for MessagesPartialUpdate for application/x-www-form-urlencoded ContentType.
type MessagesPartialUpdateFormdataRequestBody = PatchedMessage

// MessagesPartialUpdateMultipartRequestBody defines body for MessagesPartialUpdate for multipart/form-data ContentType.
type MessagesPartialUpdateMultipartRequestBody = PatchedMessage

// MessagesUpdateJSONRequestBody defines body for MessagesUpdate for application/json ContentType.
type MessagesUpdateJSONRequestBody = Message

// MessagesUpdateFormdataRequestBody defines body for MessagesUpdate for application/x-www-form-urlencoded ContentType.
type MessagesUpdateFormdataRequestBody = Message

// MessagesUpdateMultipartRequestBody defines body for MessagesUpdate for multipart/form-data ContentType.
type MessagesUpdateMultipartRequestBody = Message

// MessagesFormattedPartialUpdateJSONRequestBody defines body for MessagesFormattedPartialUpdate for application/json ContentType.
type MessagesFormattedPartialUpdateJSONRequestBody = PatchedMessage

// MessagesFormattedPartialUpdateFormdataRequestBody defines body for MessagesFormattedPartialUpdate for application/x-www-form-urlencoded ContentType.
type MessagesFormattedPartialUpdateFormdataRequestBody = PatchedMessage

// MessagesFormattedPartialUpdateMultipartRequestBody defines body for MessagesFormattedPartialUpdate for multipart/form-data ContentType.
type MessagesFormattedPartialUpdateMultipartRequestBody = PatchedMessage

// MessagesFormattedUpdateJSONRequestBody defines body for MessagesFormattedUpdate for application/json ContentType.
type MessagesFormattedUpdateJSONRequestBody = Message

// MessagesFormattedUpdateFormdataRequestBody defines body for MessagesFormattedUpdate for application/x-www-form-urlencoded ContentType.
type MessagesFormattedUpdateFormdataRequestBody = Message

// MessagesFormattedUpdateMultipartRequestBody defines body for MessagesFormattedUpdate for multipart/form-data ContentType.
type MessagesFormattedUpdateMultipartRequestBody = Message

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /)
	RootRetrieve(w http.ResponseWriter, r *http.Request)

	// (GET /messages/)
	MessagesList(w http.ResponseWriter, r *http.Request, params MessagesListParams)

	// (POST /messages/)
	MessagesCreate(w http.ResponseWriter, r *http.Request)

	// (POST /messages/bulk-delete)
	MessagesBulkDeleteCreate(w http.ResponseWriter, r *http.Request)

	// (POST /messages/bulk-delete/{format})
	MessagesBulkDeleteFormattedCreate(w http.ResponseWriter, r *http.Request, format MessagesBulkDeleteFormattedCreateParamsFormat)

	// (POST /messages/fetch-new)
	MessagesFetchNewCreate(w http.ResponseWriter, r *http.Request)

	// (POST /messages/fetch-new/{format})
	MessagesFetchNewFormattedCreate(w http.ResponseWriter, r *http.Request, format MessagesFetchNewFormattedCreateParamsFormat)

	// (GET /messages/{format})
	MessagesFormattedList(w http.ResponseWriter, r *http.Request, format MessagesFormattedListParamsFormat, params MessagesFormattedListParams)

	// (POST /messages/{format})
	MessagesFormattedCreate(w http.ResponseWriter, r *http.Request, format MessagesFormattedCreateParamsFormat)

	// (DELETE /messages/{id}/)
	MessagesDestroy(w http.ResponseWriter, r *http.Request, id int)

	// (GET /messages/{id}/)
	MessagesRetrieve(w http.ResponseWriter, r *http.Request, id int)

	// (PATCH /messages/{id}/)
	MessagesPartialUpdate(w http.ResponseWriter, r *http.Request, id int)

	// (PUT /messages/{id}/)
	MessagesUpdate(w http.ResponseWriter, r *http.Request, id int)

	// (DELETE /messages/{id}/{format})
	MessagesFormattedDestroy(w http.ResponseWriter, r *http.Request, id int, format MessagesFormattedDestroyParamsFormat)

	// (GET /messages/{id}/{format})
	MessagesFormattedRetrieve(w http.ResponseWriter, r *http.Request, id int, format MessagesFormattedRetrieveParamsFormat)

	// (PATCH /messages/{id}/{format})
	MessagesFormattedPartialUpdate(w http.ResponseWriter, r *http.Request, id int, format MessagesFormattedPartialUpdateParamsFormat)

	// (PUT /messages/{id}/{format})
	MessagesFormattedUpdate(w http.ResponseWriter, r *http.Request, id int, format MessagesFormattedUpdateParamsFormat)

	// (GET /{format})
	RootFormattedRetrieve(w http.ResponseWriter, r *http.Request, format RootFormattedRetrieveParamsFormat)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RootRetrieve operation middleware
func (siw *ServerInterfaceWrapper) RootRetrieve(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RootRetrieve(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesList operation middleware
func (siw *ServerInterfaceWrapper) MessagesList(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params MessagesListParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "is_fetched" -------------

	err = runtime.BindQueryParameter("form", true, false, "is_fetched", r.URL.Query(), &params.IsFetched)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "is_fetched", Err: err})
		return
	}

	// ------------- Optional query parameter "recipient" -------------

	err = runtime.BindQueryParameter("form", true, false, "recipient", r.URL.Query(), &params.Recipient)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipient", Err: err})
		return
	}

	// ------------- Optional query parameter "from_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_id", r.URL.Query(), &params.FromId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from_id", Err: err})
		return
	}

	// ------------- Optional query parameter "to_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_id", r.URL.Query(), &params.ToId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesList(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesBulkDeleteCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesBulkDeleteCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesBulkDeleteCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesBulkDeleteFormattedCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesBulkDeleteFormattedCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "format" -------------
	var format MessagesBulkDeleteFormattedCreateParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesBulkDeleteFormattedCreate(w, r, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFetchNewCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesFetchNewCreate(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFetchNewCreate(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFetchNewFormattedCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesFetchNewFormattedCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "format" -------------
	var format MessagesFetchNewFormattedCreateParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFetchNewFormattedCreate(w, r, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedList operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedList(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedListParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params MessagesFormattedListParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", r.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		return
	}

	// ------------- Optional query parameter "is_fetched" -------------

	err = runtime.BindQueryParameter("form", true, false, "is_fetched", r.URL.Query(), &params.IsFetched)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "is_fetched", Err: err})
		return
	}

	// ------------- Optional query parameter "recipient" -------------

	err = runtime.BindQueryParameter("form", true, false, "recipient", r.URL.Query(), &params.Recipient)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recipient", Err: err})
		return
	}

	// ------------- Optional query parameter "from_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "from_id", r.URL.Query(), &params.FromId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from_id", Err: err})
		return
	}

	// ------------- Optional query parameter "to_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "to_id", r.URL.Query(), &params.ToId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedList(w, r, format, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedCreate operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedCreate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedCreateParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedCreate(w, r, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesDestroy operation middleware
func (siw *ServerInterfaceWrapper) MessagesDestroy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesDestroy(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesRetrieve operation middleware
func (siw *ServerInterfaceWrapper) MessagesRetrieve(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesRetrieve(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesPartialUpdate operation middleware
func (siw *ServerInterfaceWrapper) MessagesPartialUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesPartialUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesUpdate operation middleware
func (siw *ServerInterfaceWrapper) MessagesUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesUpdate(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedDestroy operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedDestroy(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedDestroyParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedDestroy(w, r, id, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedRetrieve operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedRetrieve(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedRetrieveParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedRetrieve(w, r, id, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedPartialUpdate operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedPartialUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedPartialUpdateParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedPartialUpdate(w, r, id, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MessagesFormattedUpdate operation middleware
func (siw *ServerInterfaceWrapper) MessagesFormattedUpdate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "format" -------------
	var format MessagesFormattedUpdateParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MessagesFormattedUpdate(w, r, id, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RootFormattedRetrieve operation middleware
func (siw *ServerInterfaceWrapper) RootFormattedRetrieve(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "format" -------------
	var format RootFormattedRetrieveParamsFormat

	err = runtime.BindStyledParameterWithOptions("simple", "format", r.PathValue("format"), &format, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "format", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RootFormattedRetrieve(w, r, format)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/", wrapper.RootRetrieve)
	m.HandleFunc("GET "+options.BaseURL+"/messages/", wrapper.MessagesList)
	m.HandleFunc("POST "+options.BaseURL+"/messages/", wrapper.MessagesCreate)
	m.HandleFunc("POST "+options.BaseURL+"/messages/bulk-delete", wrapper.MessagesBulkDeleteCreate)
	m.HandleFunc("POST "+options.BaseURL+"/messages/bulk-delete/{format}", wrapper.MessagesBulkDeleteFormattedCreate)
	m.HandleFunc("POST "+options.BaseURL+"/messages/fetch-new", wrapper.MessagesFetchNewCreate)
	m.HandleFunc("POST "+options.BaseURL+"/messages/fetch-new/{format}", wrapper.MessagesFetchNewFormattedCreate)
	m.HandleFunc("GET "+options.BaseURL+"/messages/{format}", wrapper.MessagesFormattedList)
	m.HandleFunc("POST "+options.BaseURL+"/messages/{format}", wrapper.MessagesFormattedCreate)
	m.HandleFunc("DELETE "+options.BaseURL+"/messages/{id}/", wrapper.MessagesDestroy)
	m.HandleFunc("GET "+options.BaseURL+"/messages/{id}/", wrapper.MessagesRetrieve)
	m.HandleFunc("PATCH "+options.BaseURL+"/messages/{id}/", wrapper.MessagesPartialUpdate)
	m.HandleFunc("PUT "+options.BaseURL+"/messages/{id}/", wrapper.MessagesUpdate)
	m.HandleFunc("DELETE "+options.BaseURL+"/messages/{id}/{format}", wrapper.MessagesFormattedDestroy)
	m.HandleFunc("GET "+options.BaseURL+"/messages/{id}/{format}", wrapper.MessagesFormattedRetrieve)
	m.HandleFunc("PATCH "+options.BaseURL+"/messages/{id}/{format}", wrapper.MessagesFormattedPartialUpdate)
	m.HandleFunc("PUT "+options.BaseURL+"/messages/{id}/{format}", wrapper.MessagesFormattedUpdate)
	m.HandleFunc("GET "+options.BaseURL+"/{format}", wrapper.RootFormattedRetrieve)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabWvjOBD+K0J3H53YbffgMBxH95bCQnevlNtPJRTFmsTaypJXGicNJf/9kOy4Tuwk",
	"TdPX3XwpqT2et2dmnpHxHU10lmsFCi2N76hNUsiY//kFrGVjcD9zo3MwKMDfSAwwhGsUmb850iZjSGPK",
	"GULPXw2oAcb/VXJGYzQFBBRnOdCYWjRCjek8oIK7Z9eICYUwBuPl7PUIMEnBy1f3h1pLYMrdz0ovr4ea",
	"z5xExm7PQY0xpfEfURR1WDaQiFyAwhXx407pwsilIAsjtofnrfwohHFeXy0lzEfedKI0Mah16OF3SNCZ",
	"vmBjoRgCr5A4FxY70NBFGQrcsiyXQOOj45OuTCq4XZajKWIehyHLRb+62NdmHLLE67Th3zkbw18faLAa",
	"viqkZEOnYw26uYGJ0IV9jL3jR9gzYAtZVrBAyPyP3w2MaEx/C+8rPKzKO1zU9rzWxYxhszZyPrn3+rth",
	"8uV5aJd92mUlq+6SUCPtdHGwiRE5Cq1oTE9JFQKxYCYicdlDgb6+vizfIacXn2lAJ2Bs+exRP+pHzkud",
	"g2K5oDE96Uf9ExrQnGHq0QrdnzH4aB2KzNn9zGlML7XGS0AjYFJCZnOtbInxcRR1uTqFoStpMhWYEinU",
	"jSWoCaZADDDp/COgeK6Fm74uZgtJYQTOaHw1cP+HVbB2vVtV0NZPBxeIYRkgGEvjq7ZH3h1VZEMw3iuh",
	"vDv5YtSQstKJBey7WeWe+lGAmbkuZK6CqVNBg4opGlVWV+E8WLX7nylcyFgYZb29RVgEU4YkZZYMARSp",
	"SpcwxckZkxbWCCuNffLNAnfpHAmJYKqsOhPA60fWxdBok45I6n7piMRbqTqC6FHTwf1cajJCy6P7Tuly",
	"SOopWCSCkwmTBTgPhveW93NrZHR2LfiugKdAUjFOn80t1FudGnT3aKIVVtOM5bkUiW+l8Lt1jt81FG7i",
	"j05q9lNrOQ+tpg4osrFrzcUktnTg+FLbDa39j2cQWlITWPxYDe8nCaWmwnmwpOW2N51Oe26Q9wojQSWa",
	"l6Syu9qskChyZjD06jhD9hhFS9zsiGTeQvjoGdLySFCXpvewkDc9DhKwXBA2wv2xkDefvOzewNfLUHtT",
	"WNl7WlGeEimsH3ELwhUcFAq31lStXAbE6XZcOtjxqyYLIeK3kb2yGt6VK8d8l/Se+UcQeJ3nFfb0k8et",
	"Bo15WG42qyE3JxGoInNu9z0eg/a6MzgA2g2o5+Segul2FM+c6FeYNlpkj1m/56GhlWvPylW2FUxrOgvc",
	"6lKvOUMYaQP75GmHsl8k7FWL/teBqAnMxr29xqN7gX8mNILD0eBwNDgcDd790eAdrjCHw8grH0buBJ+H",
	"5f62OJB0F9cnsGj07EFFJfjGgnpAC354qpUy2Ey4jXd4LxFW9HaqwL/mTNL1qblgBgWT33L+0FnyqPw8",
	"/dxYeQf/xOOjQ/teU6Slbz5/42VTbOin91ctPxXLRG+ZZZqnoG1sU68yu9DOE52F3jWh1Ynbidnecube",
	"E2fW2d+dPN8YBAda/ploua7LQ0EemP8lmH/rG89LrfH1uGrwIp9s+Atm0v35xYXRvEjcP6QUqj7+Kr+M",
	"siufRiU6CydHtP0G7VwnTBIOE5A6z0Bhl7Y4DKWTS7XF+M8oiuh8MP8/AAD//xIZWw/uJwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
